// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum AdcPulseDebugOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AdcPulseDebug<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for AdcPulseDebug<'a> {
  type Inner = AdcPulseDebug<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> AdcPulseDebug<'a> {
  pub const VT_AMPLITUDE: flatbuffers::VOffsetT = 4;
  pub const VT_PEAK_AREA: flatbuffers::VOffsetT = 6;
  pub const VT_BACKGROUND: flatbuffers::VOffsetT = 8;
  pub const VT_THRESHOLD_TIME: flatbuffers::VOffsetT = 10;
  pub const VT_PEAK_TIME: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    AdcPulseDebug { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AdcPulseDebugArgs<'args>
  ) -> flatbuffers::WIPOffset<AdcPulseDebug<'bldr>> {
    let mut builder = AdcPulseDebugBuilder::new(_fbb);
    if let Some(x) = args.peak_time { builder.add_peak_time(x); }
    if let Some(x) = args.threshold_time { builder.add_threshold_time(x); }
    if let Some(x) = args.background { builder.add_background(x); }
    if let Some(x) = args.peak_area { builder.add_peak_area(x); }
    if let Some(x) = args.amplitude { builder.add_amplitude(x); }
    builder.finish()
  }


  #[inline]
  pub fn amplitude(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(AdcPulseDebug::VT_AMPLITUDE, None)}
  }
  #[inline]
  pub fn peak_area(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(AdcPulseDebug::VT_PEAK_AREA, None)}
  }
  #[inline]
  pub fn background(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(AdcPulseDebug::VT_BACKGROUND, None)}
  }
  #[inline]
  pub fn threshold_time(&self) -> Option<flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(AdcPulseDebug::VT_THRESHOLD_TIME, None)}
  }
  #[inline]
  pub fn peak_time(&self) -> Option<flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(AdcPulseDebug::VT_PEAK_TIME, None)}
  }
}

impl flatbuffers::Verifiable for AdcPulseDebug<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("amplitude", Self::VT_AMPLITUDE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("peak_area", Self::VT_PEAK_AREA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("background", Self::VT_BACKGROUND, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u64>>>("threshold_time", Self::VT_THRESHOLD_TIME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u64>>>("peak_time", Self::VT_PEAK_TIME, false)?
     .finish();
    Ok(())
  }
}
pub struct AdcPulseDebugArgs<'a> {
    pub amplitude: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub peak_area: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub background: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub threshold_time: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
    pub peak_time: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
}
impl<'a> Default for AdcPulseDebugArgs<'a> {
  #[inline]
  fn default() -> Self {
    AdcPulseDebugArgs {
      amplitude: None,
      peak_area: None,
      background: None,
      threshold_time: None,
      peak_time: None,
    }
  }
}

pub struct AdcPulseDebugBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> AdcPulseDebugBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_amplitude(&mut self, amplitude: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdcPulseDebug::VT_AMPLITUDE, amplitude);
  }
  #[inline]
  pub fn add_peak_area(&mut self, peak_area: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdcPulseDebug::VT_PEAK_AREA, peak_area);
  }
  #[inline]
  pub fn add_background(&mut self, background: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdcPulseDebug::VT_BACKGROUND, background);
  }
  #[inline]
  pub fn add_threshold_time(&mut self, threshold_time: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdcPulseDebug::VT_THRESHOLD_TIME, threshold_time);
  }
  #[inline]
  pub fn add_peak_time(&mut self, peak_time: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdcPulseDebug::VT_PEAK_TIME, peak_time);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> AdcPulseDebugBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AdcPulseDebugBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<AdcPulseDebug<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for AdcPulseDebug<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("AdcPulseDebug");
      ds.field("amplitude", &self.amplitude());
      ds.field("peak_area", &self.peak_area());
      ds.field("background", &self.background());
      ds.field("threshold_time", &self.threshold_time());
      ds.field("peak_time", &self.peak_time());
      ds.finish()
  }
}
