// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_RUN_STATE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_RUN_STATE: i8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_RUN_STATE: [RunState; 2] = [
  RunState::SETUP,
  RunState::RUNNING,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct RunState(pub i8);
#[allow(non_upper_case_globals)]
impl RunState {
  pub const SETUP: Self = Self(0);
  pub const RUNNING: Self = Self(1);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::SETUP,
    Self::RUNNING,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::SETUP => Some("SETUP"),
      Self::RUNNING => Some("RUNNING"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for RunState {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for RunState {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for RunState {
    type Output = RunState;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for RunState {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for RunState {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for RunState {}
pub enum ISISDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ISISData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ISISData<'a> {
  type Inner = ISISData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ISISData<'a> {
  pub const VT_PERIOD_NUMBER: flatbuffers::VOffsetT = 4;
  pub const VT_RUN_STATE: flatbuffers::VOffsetT = 6;
  pub const VT_PROTON_CHARGE: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ISISData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ISISDataArgs
  ) -> flatbuffers::WIPOffset<ISISData<'bldr>> {
    let mut builder = ISISDataBuilder::new(_fbb);
    builder.add_proton_charge(args.proton_charge);
    builder.add_period_number(args.period_number);
    builder.add_run_state(args.run_state);
    builder.finish()
  }


  #[inline]
  pub fn period_number(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ISISData::VT_PERIOD_NUMBER, Some(0)).unwrap()}
  }
  #[inline]
  pub fn run_state(&self) -> RunState {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RunState>(ISISData::VT_RUN_STATE, Some(RunState::SETUP)).unwrap()}
  }
  #[inline]
  pub fn proton_charge(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(ISISData::VT_PROTON_CHARGE, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ISISData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("period_number", Self::VT_PERIOD_NUMBER, false)?
     .visit_field::<RunState>("run_state", Self::VT_RUN_STATE, false)?
     .visit_field::<f32>("proton_charge", Self::VT_PROTON_CHARGE, false)?
     .finish();
    Ok(())
  }
}
pub struct ISISDataArgs {
    pub period_number: u32,
    pub run_state: RunState,
    pub proton_charge: f32,
}
impl<'a> Default for ISISDataArgs {
  #[inline]
  fn default() -> Self {
    ISISDataArgs {
      period_number: 0,
      run_state: RunState::SETUP,
      proton_charge: 0.0,
    }
  }
}

pub struct ISISDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ISISDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_period_number(&mut self, period_number: u32) {
    self.fbb_.push_slot::<u32>(ISISData::VT_PERIOD_NUMBER, period_number, 0);
  }
  #[inline]
  pub fn add_run_state(&mut self, run_state: RunState) {
    self.fbb_.push_slot::<RunState>(ISISData::VT_RUN_STATE, run_state, RunState::SETUP);
  }
  #[inline]
  pub fn add_proton_charge(&mut self, proton_charge: f32) {
    self.fbb_.push_slot::<f32>(ISISData::VT_PROTON_CHARGE, proton_charge, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ISISDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ISISDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ISISData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ISISData<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ISISData");
      ds.field("period_number", &self.period_number());
      ds.field("run_state", &self.run_state());
      ds.field("proton_charge", &self.proton_charge());
      ds.finish()
  }
}
