stages:
  - build

build_debug:
  stage: build
  variables:
    GIT_STRATEGY: clone
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - te7grebe_non_sudo
  before_script:
    - whoami
  script:
    - echo "Build Release start - make env file with CI_JOB_ID for release step"
    - echo BUILD_JOB_ID=$CI_JOB_ID >> CI_JOB_ID.env
    - cargo build
    - ls
  artifacts:
    paths:
      - target/debug/rust-data-stream-processor
    reports: # export the environment statement so we can access it in the release stage
      dotenv: CI_JOB_ID.env

build_release:
  stage: build
  needs:
    - job: build_debug
  variables:
    GIT_STRATEGY: clone
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - te7grebe_non_sudo
  before_script:
    - whoami
  script:
    - echo "Build Release start - make env file with CI_JOB_ID for release step"
    - echo BUILD_JOB_ID=$CI_JOB_ID >> CI_JOB_ID.env
    - cargo build --release
    - ls
  artifacts:
    paths:
      - target/release/rust-data-stream-processor
    reports: # export the environment statement so we can access it in the release stage
      dotenv: CI_JOB_ID.env