# UDP address to bind to
udp_bind_addr = "127.0.0.1:12345"

# Kafka topic to write flatbuffered messages to
dest_kafka_topic = "instrument_rawEvents"

# Path to wiring CSV file
wiring_csv_path = "./src/config/wiring.csv"

# Address on which to bind metrics server
metrics_bind_addr = "127.0.0.1:8484"

[kafka_producer]
"bootstrap.servers" = "itachi.isis.cclrc.ac.uk:9092"
"message.timeout.ms" = "5000"
