// automatically generated by the FlatBuffers compiler, do not modify


// @generated
mod dtdb_adc_pulse_debug_generated;       // Tweaked from generated to allow to import as module
mod is84_isis_events_generated;           // Tweaked from generated to allow to import as module
use dtdb_adc_pulse_debug_generated::*;    // Tweaked from generated to allow to import as module
use is84_isis_events_generated::*;        // Tweaked from generated to allow to import as module
use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FACILITY_DATA: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FACILITY_DATA: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FACILITY_DATA: [FacilityData; 3] = [
  FacilityData::NONE,
  FacilityData::ISISData,
  FacilityData::AdcPulseDebug,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FacilityData(pub u8);
#[allow(non_upper_case_globals)]
impl FacilityData {
  pub const NONE: Self = Self(0);
  pub const ISISData: Self = Self(1);
  pub const AdcPulseDebug: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::ISISData,
    Self::AdcPulseDebug,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::ISISData => Some("ISISData"),
      Self::AdcPulseDebug => Some("AdcPulseDebug"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for FacilityData {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for FacilityData {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for FacilityData {
    type Output = FacilityData;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for FacilityData {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for FacilityData {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for FacilityData {}
pub struct FacilityDataUnionTableOffset {}

pub enum EventMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EventMessage<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EventMessage<'a> {
  type Inner = EventMessage<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EventMessage<'a> {
  pub const VT_SOURCE_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_MESSAGE_ID: flatbuffers::VOffsetT = 6;
  pub const VT_PULSE_TIME: flatbuffers::VOffsetT = 8;
  pub const VT_TIME_OF_FLIGHT: flatbuffers::VOffsetT = 10;
  pub const VT_DETECTOR_ID: flatbuffers::VOffsetT = 12;
  pub const VT_FACILITY_SPECIFIC_DATA_TYPE: flatbuffers::VOffsetT = 14;
  pub const VT_FACILITY_SPECIFIC_DATA: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EventMessage { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EventMessageArgs<'args>
  ) -> flatbuffers::WIPOffset<EventMessage<'bldr>> {
    let mut builder = EventMessageBuilder::new(_fbb);
    builder.add_pulse_time(args.pulse_time);
    builder.add_message_id(args.message_id);
    if let Some(x) = args.facility_specific_data { builder.add_facility_specific_data(x); }
    if let Some(x) = args.detector_id { builder.add_detector_id(x); }
    if let Some(x) = args.time_of_flight { builder.add_time_of_flight(x); }
    if let Some(x) = args.source_name { builder.add_source_name(x); }
    builder.add_facility_specific_data_type(args.facility_specific_data_type);
    builder.finish()
  }


  #[inline]
  pub fn source_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(EventMessage::VT_SOURCE_NAME, None)}
  }
  #[inline]
  pub fn message_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(EventMessage::VT_MESSAGE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn pulse_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(EventMessage::VT_PULSE_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn time_of_flight(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(EventMessage::VT_TIME_OF_FLIGHT, None)}
  }
  #[inline]
  pub fn detector_id(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(EventMessage::VT_DETECTOR_ID, None)}
  }
  #[inline]
  pub fn facility_specific_data_type(&self) -> FacilityData {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<FacilityData>(EventMessage::VT_FACILITY_SPECIFIC_DATA_TYPE, Some(FacilityData::NONE)).unwrap()}
  }
  #[inline]
  pub fn facility_specific_data(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(EventMessage::VT_FACILITY_SPECIFIC_DATA, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn facility_specific_data_as_isisdata(&self) -> Option<ISISData<'a>> {
    if self.facility_specific_data_type() == FacilityData::ISISData {
      self.facility_specific_data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ISISData::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn facility_specific_data_as_adc_pulse_debug(&self) -> Option<AdcPulseDebug<'a>> {
    if self.facility_specific_data_type() == FacilityData::AdcPulseDebug {
      self.facility_specific_data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { AdcPulseDebug::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for EventMessage<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("source_name", Self::VT_SOURCE_NAME, false)?
     .visit_field::<u64>("message_id", Self::VT_MESSAGE_ID, false)?
     .visit_field::<u64>("pulse_time", Self::VT_PULSE_TIME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("time_of_flight", Self::VT_TIME_OF_FLIGHT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("detector_id", Self::VT_DETECTOR_ID, false)?
     .visit_union::<FacilityData, _>("facility_specific_data_type", Self::VT_FACILITY_SPECIFIC_DATA_TYPE, "facility_specific_data", Self::VT_FACILITY_SPECIFIC_DATA, false, |key, v, pos| {
        match key {
          FacilityData::ISISData => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ISISData>>("FacilityData::ISISData", pos),
          FacilityData::AdcPulseDebug => v.verify_union_variant::<flatbuffers::ForwardsUOffset<AdcPulseDebug>>("FacilityData::AdcPulseDebug", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct EventMessageArgs<'a> {
    pub source_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub message_id: u64,
    pub pulse_time: u64,
    pub time_of_flight: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub detector_id: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub facility_specific_data_type: FacilityData,
    pub facility_specific_data: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for EventMessageArgs<'a> {
  #[inline]
  fn default() -> Self {
    EventMessageArgs {
      source_name: None,
      message_id: 0,
      pulse_time: 0,
      time_of_flight: None,
      detector_id: None,
      facility_specific_data_type: FacilityData::NONE,
      facility_specific_data: None,
    }
  }
}

pub struct EventMessageBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EventMessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_source_name(&mut self, source_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EventMessage::VT_SOURCE_NAME, source_name);
  }
  #[inline]
  pub fn add_message_id(&mut self, message_id: u64) {
    self.fbb_.push_slot::<u64>(EventMessage::VT_MESSAGE_ID, message_id, 0);
  }
  #[inline]
  pub fn add_pulse_time(&mut self, pulse_time: u64) {
    self.fbb_.push_slot::<u64>(EventMessage::VT_PULSE_TIME, pulse_time, 0);
  }
  #[inline]
  pub fn add_time_of_flight(&mut self, time_of_flight: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EventMessage::VT_TIME_OF_FLIGHT, time_of_flight);
  }
  #[inline]
  pub fn add_detector_id(&mut self, detector_id: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EventMessage::VT_DETECTOR_ID, detector_id);
  }
  #[inline]
  pub fn add_facility_specific_data_type(&mut self, facility_specific_data_type: FacilityData) {
    self.fbb_.push_slot::<FacilityData>(EventMessage::VT_FACILITY_SPECIFIC_DATA_TYPE, facility_specific_data_type, FacilityData::NONE);
  }
  #[inline]
  pub fn add_facility_specific_data(&mut self, facility_specific_data: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EventMessage::VT_FACILITY_SPECIFIC_DATA, facility_specific_data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EventMessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EventMessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EventMessage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EventMessage<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EventMessage");
      ds.field("source_name", &self.source_name());
      ds.field("message_id", &self.message_id());
      ds.field("pulse_time", &self.pulse_time());
      ds.field("time_of_flight", &self.time_of_flight());
      ds.field("detector_id", &self.detector_id());
      ds.field("facility_specific_data_type", &self.facility_specific_data_type());
      match self.facility_specific_data_type() {
        FacilityData::ISISData => {
          if let Some(x) = self.facility_specific_data_as_isisdata() {
            ds.field("facility_specific_data", &x)
          } else {
            ds.field("facility_specific_data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        FacilityData::AdcPulseDebug => {
          if let Some(x) = self.facility_specific_data_as_adc_pulse_debug() {
            ds.field("facility_specific_data", &x)
          } else {
            ds.field("facility_specific_data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("facility_specific_data", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `EventMessage`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_event_message_unchecked`.
pub fn root_as_event_message(buf: &[u8]) -> Result<EventMessage, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<EventMessage>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `EventMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_event_message_unchecked`.
pub fn size_prefixed_root_as_event_message(buf: &[u8]) -> Result<EventMessage, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<EventMessage>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `EventMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_event_message_unchecked`.
pub fn root_as_event_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EventMessage<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<EventMessage<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `EventMessage` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_event_message_unchecked`.
pub fn size_prefixed_root_as_event_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EventMessage<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<EventMessage<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a EventMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `EventMessage`.
pub unsafe fn root_as_event_message_unchecked(buf: &[u8]) -> EventMessage {
  flatbuffers::root_unchecked::<EventMessage>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed EventMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `EventMessage`.
pub unsafe fn size_prefixed_root_as_event_message_unchecked(buf: &[u8]) -> EventMessage {
  flatbuffers::size_prefixed_root_unchecked::<EventMessage>(buf)
}
pub const EVENT_MESSAGE_IDENTIFIER: &str = "ev42";

#[inline]
pub fn event_message_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, EVENT_MESSAGE_IDENTIFIER, false)
}

#[inline]
pub fn event_message_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, EVENT_MESSAGE_IDENTIFIER, true)
}

#[inline]
pub fn finish_event_message_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<EventMessage<'a>>) {
  fbb.finish(root, Some(EVENT_MESSAGE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_event_message_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<EventMessage<'a>>) {
  fbb.finish_size_prefixed(root, Some(EVENT_MESSAGE_IDENTIFIER));
}
